### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by gusty** [fable-compiler/repl#104]
I clone the repo, run `build` and this is what I get:

```
Finished Target: Restore
Starting Target: NpmInstall (==> Restore)
C:\Repos\repl\packages\Npm.js\tools\npm.cmd install
Running build failed.
Error:
System.Exception: Start of process C:\Repos\repl\packages\Npm.js\tools\npm.cmd failed. The system cannot find the file specified
   at Fake.NpmHelper.run(NpmParams npmParams) in D:\code\fake\src\app\FakeLib\NpmHelper.fs:line 105
   at FSI_0005.Build.clo@156-8.Invoke(Unit _arg5) in C:\Repos\repl\build.fsx:line 157
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target              Duration
------              --------
Clean               00:00:00.0047006
InstallDotNetCore   00:00:00.2637158
Restore             00:00:01.4036056
NpmInstall          Failure
Total:              00:00:01.7790084
---------------------------------------------------------------------
Status:             Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.Exception: Start of process C:\Repos\repl\packages\Npm.js\tools\npm.cmd failed. The system cannot find the file specified
   at Fake.NpmHelper.run(NpmParams npmParams) in D:\code\fake\src\app\FakeLib\NpmHelper.fs:line 105
   at FSI_0005.Build.clo@156-8.Invoke(Unit _arg5) in C:\Repos\repl\build.fsx:line 157
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
---------------------------------------------------------------------
```

On Windows 10

**Comment by MangelMaxime** [comment]
I can't reproduce, do you have `npm` installed and accessible from your console?

**Comment by MangelMaxime** [comment]
I reworked the build system so hopefully the problem is now solved. You can also open the repo in Gitpod (see the button in the README)

Please fill free to re-open the issue if needed.

**Comment by gusty** [comment]
Thanks, I switched to other stuff since I found this problem, but will come back later and give it a try and let you know how it goes.

**Comment by gusty** [comment]
I just came back to this.
Looks like now I'm able to compile it and run it locally.

Btw: I would add to the readme the exact command line to do this as it might not be obvious to say 

> run the WatchApp FAKE target

**Comment by MangelMaxime** [comment]
Thank you for the suggestion, I updated the README.md
